### PR TITLE
Set UPBOUND_CONTEXT env var in provider deployment

### PR DESCRIPTION
**Pull request by hasheddan**
### Description of your changes

Updates provider deployment ot include setting UPBOUND_CONTEXT
environment variable.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

`make test`

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by muvaf — APPROVED** [review]
Thanks!

**Comment by turkenh** [comment]
I just noticed that this change is not in `[release-1.10](https://github.com/upbound/crossplane/blob/release-1.10/internal/controller/pkg/revision/deployment.go#L51)`, probably because it is not cherry-picked as part of the documented release process [here](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#sync-a-new-release-branch).

It looks like the approach we are following is not scaling well as we have more divergence from the upstream crossplane.
/cc @phisco

**Comment by hasheddan** [comment]
@turkenh I believe this was intentionally dropped as it is not longer required

**Pull request merged**
